service: adhan-routines

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-3
  deploymentBucket:
    name: adhan-skill-deployment-bucket
  environment:
    TABLE: AdhanUsers
    STATS_TABLE: AdhanStats
    CLIENT_ID: ${env:CLIENT_ID, ''}
    CLIENT_SECRET: ${env:CLIENT_SECRET, ''}
    TRIGGER_STAGE: development
    TRIGGER_NAME: AdhanTime
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:${self:provider.region}:*:*
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:DescribeTable
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/AdhanUsers
            - arn:aws:dynamodb:${self:provider.region}:*:table/AdhanStats
        - Effect: Allow
          Action:
            - events:DescribeRule
            - events:PutRule
            - events:PutTargets
            - events:RemoveTargets
            - events:DeleteRule
          Resource: "*"
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:PutParameter
            - ssm:DeleteParameter
          Resource: arn:aws:ssm:${self:provider.region}:*:parameter/serverless-framework/*
        - Effect: Allow
          Action:
            - s3:CreateBucket
            - s3:PutObject
            - s3:DeleteObject
            - s3:ListBucket
            - s3:GetObject
          Resource: "*"

package:
  individually: true
  patterns:
    - '!**/*'                           # ignore tout par défaut
    - 'backend-scheduler/**'            # inclut seulement ton code backend
    - '!backend-scheduler/node_modules/**'
    - 'backend-scheduler/node_modules/luxon/**'
    - 'backend-scheduler/node_modules/node-fetch/**'
    - 'backend-scheduler/node_modules/adhan/**'

functions:
  schedulerMinute:
    name: adhan-scheduler-minute
    handler: backend-scheduler/index.handler
    events:
      - eventBridge:
          schedule: rate(1 minute)

  nightly:
    name: adhan-nightly
    handler: backend-scheduler/index.nightlyHandler
    events:
      - eventBridge:
          schedule: rate(1 hour)

resources:
  Resources:
    AdhanStatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AdhanStats
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH

    AdhanUsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AdhanUsers
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
